### ISSUE TITLE
image preprocessing step

### ISSUE THREAD

**Issue by Strateus** [AKSHAYUBHAT/TensorFace#1]
I see in your vggface/torch_verify.ipynb that you do following preprocessing steps:
1. rescale image to 224x224 - thats clear for me as inputs required to be this size
2. rescale each channel to 255 - i have question about this where in VGG description you found that you need to do this? or maybe you have some understanding regarding this step?
3. convert to BGR - this is not described as well, but i suppose you use Caffe model, and Caffe use BGR, thats why you do this conversion?
4. subtract image mean - i have 2 questions here: mean image can be per pixel and per channel, you use per channel, why per channel, not per pixel? and second question - where did you get it? VGG did not publish these numbers as i know
5. Why you do not divide every pixel by 255? I did not see any information in VGG paper about this as well, but some frameworks do this, some dont, and im not sure if we need to do this or no for VGG face

EDIT:
question #2: i guess Torch loads image not scaled to 255, so please skip this

**Comment by AKSHAYUBHAT** [comment]
The rescale by 255 is due to the way Torch image loads an image. The pixel values are between 0 and 1, instead of 0 and 255. All these steps are exactly same as those described here http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

**Comment by AKSHAYUBHAT** [comment]
specifically http://www.robots.ox.ac.uk/~vgg/software/vgg_face/src/vgg_face_torch.tar.gz

**Comment by Strateus** [comment]
Thank you
