### ISSUE TITLE
About tensorflow-face

### ISSUE THREAD

**Issue by anguoyang** [AKSHAYUBHAT/TensorFace#3]
Dear ASkshay Bhat,

Tensorflow-face is an interesting project which combine tensorflow and openface, I really want to do some tests on it,
however, I do not know how to start, and there is no document on compiling/run, have you tested on some face images?
and how about the result compare with openface? thanks.

B.R
Anguo

**Comment by AKSHAYUBHAT** [comment]
HI, I will update readme over next few weeks. Regarding your question, OpenFace is a better alternative than ported VGG Face recognition network. 
The code in this repo can be run with only tensor flow installed. See the iPython notebook for an example. I will add detailed instructions soon.

**Comment by trungdn** [comment]
I'm also very interested in this project. Hope you can have an instructions soon. I already intstalled tensorflow. Thank you very much.
