### ISSUE TITLE
use network.h5 as weight

### ISSUE THREAD

**Issue by Ripppah** [AKSHAYUBHAT/TensorFace#7]
Hi,

I am trying to use your pre-trained weight network.h5 to train new faces. Could you give me some details about this file? such as input data size and variables? I am not familiar with working with HDF5 file in tensor flow.

Thanks

**Comment by AKSHAYUBHAT** [comment]
You can find those details here https://github.com/AKSHAYUBHAT/TensorFace/blob/master/vggface/torch_verify.ipynb
